### ISSUE TITLE
Handle spellchecking, autocorrect and autocompletion

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-typing#3] opened 2016-04-21 14:06 UTC
As I mentioned in #2 it makes sense to handle these features in this package.

However, while typing should be straightforward (with the exception of composition, but we should be fine here too), spellchecking and autocorrect may be a bit tricky because they may cover a bigger part of a tree. Additionally, I'm a bit worried about touch devices with onscreen keyboards, so they will need to be checked separately.

Note: If you ever test autocorrection on touch devices make sure to use English keyboard because (at least on iOS) it has more features than the Polish one.

**Comment by Reinmar** [comment] 2016-04-21 14:09
BTW. This is lovely:

![screen shot 2016-04-21 at 15 54 15](https://cloud.githubusercontent.com/assets/156149/14711869/51c2667e-07db-11e6-995a-5d5449b7fd78.png)


![screen shot 2016-04-21 at 15 54 30](https://cloud.githubusercontent.com/assets/156149/14711870/54415766-07db-11e6-8f9b-277c7e59673e.png)

**Comment by Reinmar** [comment] 2016-04-21 14:19
On Firefox it works better – there are suggestions through inline styles.

There are three main situations possible:

```html
1.
<p>or<strong>ege.</strong></p>

2.
<p>or<strong>e</strong>nge</p>

3.
<p>or<strong>enge</strong></p>
```

In the first one we'll have mutation with two text node changes – `or -> orange` and `ege. -> .`. This is rather trivial to handle.

In the second one there's a bit of a mess, because number of children changes and figuring out what happened may be tricky.

In the third case at least Firefox left empty `<strong>` and modified both text nodes (`or -> orange` and `enge -> (empty)`).

**Comment by Reinmar** [comment] 2016-04-26 15:13
There's more. After we handled all mutations coming from a spellchecker or autocorrection the caret should be placed where the browser keeps it natively. This can be at the end of corrected word or even further (e.g. if correction is triggered by typing a space after an incorrect word, the selection should stay after that space).

To do that we need to have the real DOM selection with the mutations. This is tricky though, because the selection may not be anchored in nodes that are present in the view – it may need to point to nodes which come with the mutation event. This isn't yet supported, but @pjasiun is working on it.

For now, we're placing the caret after the last change that was done to the content.

**Comment by Reinmar** [comment] 2016-05-27 09:35
One thing that came to my mind while implementing basic typing support, was that changes done when correcting a word by spell checker should be handled differently than typed text (should have their own undo steps). 

Unfortunately, this doesn't seem to be easy to implement. We'd need a very good heuristic able to differentiate spell checking and auto correction as you type (this should behave as normal typing).

**Comment by pjasiun** [comment] 2016-05-30 10:36
There is a ticket about the selection in the mutations: https://github.com/ckeditor/ckeditor5-engine/issues/399 It does not seems to be simple, but is seems to be important and need to be closed soon to handle cases like these.

**Comment by f1ames** [comment] 2017-02-28 09:29
I created additional manual test (`t/3`) and a codepen with plain contenteditable to test and compare how spellchecking works:

http://localhost:8125/ckeditor5-typing/tests/manual/spellchecking.html
http://codepen.io/f1ames/pen/RpWrRd

![image](https://cloud.githubusercontent.com/assets/1061942/23396152/8a998434-fd92-11e6-850d-a93f3c5389ec.png)

# Chrome

### Plain text cases
All cases are handled correctly (words corrected and caret placed after) same as in plain contenteditable.

### Styled text
**The spellchecking in context menu is fired for the following cases**:

* collapsed selection (but not on the boundaries of the inline style): `or<strong>e[]nge</strong>` but not `or<strong>[]enge</strong>`
* selection containing whole part with one inline style of the word: `or<strong>[enge]</strong>` but not `or<strong>[en]ge</strong>`

For all other cases the earlier mentioned `Look Up "..."` is fired.

**How correcting words work in those cases**:

While Chrome considers whole styled word as a one (assuming based on a proposed correct word) the correction itself is applied only to a part of the word within the same inline style (in plain contenteditable):

* `[or]<strong>enge</strong>` -> `orange[]<strong>enge</strong>`
* `or<strong>en[]ge</strong>` -> `or<strong>orange[]</strong>`

In the current state of implementation of the editor it works like the above only for plain text parts of the word (`[or]<strong>enge</strong>`) while corrections on styled parts are ignored / not processed.

# Firefox

### Plain text cases
All cases are handled correctly (words corrected and caret placed after) same as in plain contenteditable. The only difference is that Firefox does not propose corrections which
covers more than one word (see `hous e` or `Foo athat`).
![image](https://cloud.githubusercontent.com/assets/1061942/23396825/f1a20e96-fd95-11e6-86ae-866e3452a7a4.png)

### Styled text
No matter which part of styled text was clicked, the context menu always contains words for correction. Natively, the corrected word uses the style which is present on the word beginning:

* `or<strong>enge</strong>` -> `orange`
* `<strong>ore</strong>nge` -> `<strong>orange</strong>`
* `<em>co</em>mu<strong>ter</strong>` -> `<em>computer</em>`

In the current state of implementation of the editor it works quite different than native implementation:

* `or<strong>enge</strong>` -> `orange<strong>enge</strong>`
* `<strong>ore</strong>nge` -> `nge`
* `<em>co</em>mu<strong>ter</strong>` -> `mu<strong>ter</strong>`

# Safari

### Plain text cases
All cases are handled correctly (words corrected) but the caret is placed on the beginning of the word in the editor while natively the whole corrected word is selected after correction.
Also the corrections works same as in the Firefox - no corrections which covers more than one word.

### Styled text
The spellchecking in context menu is fired for collapsed selection inside incorrect word or while the whole word is selected (partial selection fires `Look Up "..."` even for plain text corrections).

Natively, the corrected word uses the style which is present on the word beginning:

* `or<strong>enge</strong>` -> `orange`
* `<strong>ore</strong>nge` -> `<strong>orange</strong>`
* `<em>co</em>mu<strong>ter</strong>` -> `<em>computer</em>`

In the current state of implementation of the editor, corrections are simply not processed (nothing changes) and selection stays as it was (covering the whole word).

### Additional mechanisms
Safari has additional spell checking mechanisms:

1&period; The incorrect word is corrected right after pressing space while typing:

* Natively, it works for both plain and styled words (the styles for corrected words are applied same as when using context menu).
* In the current state of implementation of the editor, it works for plain words, but for styled words corrections are ignored (same as with context menu) and pressing space does nothing (which means space is not inserted).

2&period; The additional panel appears while typing and correct word might be selected (the selection then is placed after corrected word):
![image](https://cloud.githubusercontent.com/assets/1061942/23399470/9d5bc042-fda0-11e6-9bfc-908cfad46437.png)
* Natively, it works for both plain and styled words (the styles for corrected words are applied same as when using context menu).
* In the current state of implementation of the editor, it works for plain words, but for styled words corrections are ignored (same as with context menu). Selection is placed after word.

**Comment by Reinmar** [comment] 2017-02-28 11:09
Great research! Does it mean that everything works fine (or acceptably well) now and we can close the task? Or are you going to check mobile browsers too?

**Comment by f1ames** [comment] 2017-02-28 11:17
1. I need to test mobiles too (Android, iOS).
2. Apart from manual test I added, some integration tests would be useful.

To stabilize spellchecking we need to take care of #26 (not sure if still reproducible - see https://github.com/ckeditor/ckeditor5-typing/issues/26#issuecomment-282999378), #54 and #73 IMHO. Not sure it is that important to be included in 1.0.0, but I suppose yes.

The biggest issue here is with spell checking working with styled words. The correction of a styled words also needs some additional work (as you may see in the research).
The approach working natively in FF and Safari (the whole word is replaced and styled according to the styles present on the beginning of the word) seems like a reasonable solution, but it may required quite a lot of work (especially if we would like to have consistent behavior in all browsers - see Chrome). As @Reinmar mentioned
> We'd need a very good heuristic able to differentiate spell checking and auto correction as you type (this should behave as normal typing).

So I am not entirely sure when and how exactly we should handle it.

**Comment by Reinmar** [comment] 2017-02-28 11:36
I think we can live with #54 for a while (it's just an annoyance), #26 is indeed fixed already and #73 I think is invalid. So this leaves us with missing integration tests and more testing on mobiles :). Great news :)

**Comment by fredck** [comment] 2017-02-28 12:58
Add "markers" to the problem with "styled words". I've heard from @pjasiun that markers also have an impact on native spellchecking.

**Comment by Reinmar** [comment] 2017-02-28 13:03
They definitely do. Most likely similarly to inline formatting. But I guess it can only be checked in an editor using markers extensively.

**Comment by f1ames** [comment] 2017-02-28 13:41
Well, I suppose it might be even a bigger issue with markers. I am not sure exactly how markers are implemented but while with inline styles we might be able to decide how corrected word should be styled it might be more tricky with markers and how they should change after word correction.

Anyway, I think handling spell checking with styled text and text with markers deserves separate issue, I will create it soon.

**Comment by f1ames** [comment] 2017-03-01 08:53
There are basically 3 mechanisms connected to spell checking on mobiles (correct me if I mixed the definitions):
- Spell checking - selecting the word and using suggestions which will replace it with the correct form.
- Autocorrect - when typing, incorrect word is automatically corrected after pressing/typing space.
- Autocomplete - the words are suggested while typing and will be inserted separated by space from the previous word.

# Android (Chrome)

## Spellchecking

Corrections are only available for collapsed selection.

### Plain text
Works as expected for plain contenteditable and the editor (words corrected and caret placed after).

### Styled text
Natively, it works similar to desktop Firefox/Safari. The whole word (together with styling) is replaced. However, the styles of the new inserted word are not taken from its beginning but from the current selection, so:

* `o[]r<strong>enge</strong>`  -> `orange`
* `or<strong>eng[]e</strong>` -> `<strong>orange</strong>`

The editor produces the following results:

* `o[]r<strong>enge</strong>`  -> `ooranger<strong>enge</strong>`
* `or<strong>eng[]e</strong>`  -> `orangeor<strong>e</strong>`
* `o[]r<strong>e</strong>nge`  -> `ooranger<strong>e</strong>nge`
* `or<strong>e[]</strong>nge`  -> `or<strong>eorange</strong>nge`
* `<strong>ore</strong>n[]ge` -> `<strong>ore</strong>norangege`
* `<strong>o[]re</strong>nge` -> `nge`

Which seems like in most cases, styled part of text before selection is removed and the correct word is inserted, without removing redundant parts of the text.

## Autocorrect

### Plain text
Works as expected for plain contenteditable and the editor (words corrected and caret placed after, separated by space from corrected word).

### Styled text
It seems like partially styled words are not corrected in the same manner as plain text. The behavior is similar in plain contenteditable and the editor and it seems corrections are triggered less often.
One thing to notice is that in plain contenteditable sometimes word are autocorrected in a way that the word does not change but its styling does, e.g. `<strong>or</strong>enge`  becomes `<strong>orenge</strong>`. The same happens in the editor which means for that cases the behavior is consistent with the native one.

## Autocomplete
Works fine for both plain and styled words. The inserted words are separated by space and properly styled (so the word inserted after bolded word is also bolded).

# iOS (Safari)

## Spellchecking

### Plain text
The spell checking bubble appears only when whole incorrect word is selected (automatically selected after tapping on it). Works as expected in the editor and same as in the plain contenteditable.

### Styled text
In plain contenteditable it works same as in Mac/Desktop Safari.
In the editor, it does not work in most cases (nothing is inserted and selection does not change). There are some cases in which some text is inserted/removes but works different than in the plain contenteditable and messes up content, e.g.
`The new <strong>co</strong>mu<em>ter</em> is.` -> replacing `comuter` with `computer` -> `The new <strong>co</strong>mu is.`

## Autocorrect

### Plain text
Works as expected in the editor and same as in plain contenteditable.

### Styled
In plain contenteditable, correction behaves same as a spell checking ones.
In the editor, the correction is just ignored (text does not change) but space is inserted so it does not influence further typing.

## Autocomplete
Works fine for both plain and styled words. The inserted words are separated by space and properly styled (so the word inserted after bolded word is also bolded).

**Comment by f1ames** [comment] 2017-03-01 09:01
Extracted #74 covering styled text / text with markers.

**Comment by Reinmar** [comment] 2017-03-01 09:04
Superb :)! Thanks for the details. 

So I can see that spellchecking styled words doesn't work well. But the combination of a misspelt word and a word which is partially styled should be a really rare situation, so we don't have to be worried about this atm. We can extract this to a separate ticket.

Also, if I missed some other issues, please report them too. Let's have all issues reported because the status of things will change with time so this analysis will get outdated. It'll be easier to track the issues separately.

**Comment by f1ames** [comment] 2017-03-01 09:24
Ok, so for this issue, only integration test are missing, I will take care of that now.

> Also, if I missed some other issues, please report them too. Let's have all issues reported because the status of things will change with time so this analysis will get outdated. It'll be easier to track the issues separately.

Do you mean to report those specific issue with styled text or any other issues (not connected to styled text) encountered during research/testing?

**Comment by Reinmar** [comment] 2017-03-01 09:32
Having one issue for styled text and text with markers (https://github.com/ckeditor/ckeditor5-typing/issues/74) for all operations (spell checking, autocorrect, etc) is perfect. Good decision, because that's a single big topic.

So what I meant were some additional, unrelated issues which you might've found. But I've seen you reported some already, so I guess it's all done.

**Comment by f1ames** [comment] 2017-03-01 10:15
Reported two additional issues: #76 and https://github.com/ckeditor/ckeditor5-basic-styles/issues/38.

**Comment by f1ames** [comment] 2017-03-01 11:39
Found one additional issue in FF -> #77.

**Comment by f1ames** [comment] 2017-03-01 12:03
I added some unit tests which uses same mutation like the one generated by `MutationObserver` based on a native mutations generated by spellchecking - https://github.com/ckeditor/ckeditor5-typing/commit/f06a22e599af7d3b3a3b26b6e19d6f23afe904bd.

Should we also have some test which will be based on firing mocks of native mutations (so it will also test the `MutationObserver`) or emulating mutations like above is enough?

**Comment by Reinmar** [comment] 2017-03-01 17:19
> Should we also have some test which will be based on firing mocks of native mutations (so it will also test the MutationObserver) or emulating mutations like above is enough?

I guess we should either have one or the other... or a reasonable mix of both :D. Now, we simulate firing our mutation events which is so-so. I don't like such low-level unit tests which test pretty much nothing, except a few lines of code in this feature. So, usually, I just go with more integration tests. OTOH, browsers tend to be unstable if you're doing too many real-life editing operations (which are also slow) so it's good to avoid them if you can. So having unit tests like the current ones make sense too.

Therefore (and since it doesn't make sense to rebuild all the tests now) we can add just a couple of integration tests to enrich the current suite. I'd propose checking if we can test this by doing real changes in the DOM (text nodes and selection). E.g. we could use native `execCommnd( 'insertText' )`. This should give us the closest to reality simulation.

**Closed** 2017-03-03 14:28 UTC
Labels: status:confirmed, status:onreview, type:enhancement

**Comment by TatianaAU** [comment] 2019-10-08 10:43
For iOS WKWebView, is it possible to disable quicktype and predictive keyboard(i.e. suggestions and corrections) in the ckeditor5, inline? like this:
 <textarea id="content" spellcheck="false" autocorrect="off" autocomplete="off"></textarea>

This is a security requirement in our application, because the text typed by the user is shared between the applications on the phone, it is not good.

**Comment by Reinmar** [comment] 2019-10-08 19:53
Could you, please, open a new ticket? It's unclear what you're referring to. Whether it's a bug report, what's happening and what's the expected behaviour.
